[package]
name = "fast-glob"
version = "0.1.0"
description = "An extremely fast glob matcher"
repository = "https://github.com/shulaoda/fast-glob.git"
authors = [
    "Devon Govett <devongovett@gmail.com>",
    "shulaoda <laipichan@qq.com>",
]
license = "MIT"
edition = "2021"

[dev-dependencies]
criterion = "0.5.1"
glob = "0.3.1"
globset = "0.4.14"

[[test]]
name = "test"
path = "tests/test.rs"


[[bench]]
name = "bench"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
