[package]
name = "glob-match"
version = "0.1.0"
authors = ["Devon Govett <devongovett@gmail.com>"]
edition = "2021"

[dev-dependencies]
criterion = "0.4.0"
glob = "*"
globset = "*"

[[bench]]
name = "bench"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
